// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorMsg.proto

package protos;

public final class SensorProtos {
  private SensorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_intelligence_SensorMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_intelligence_SensorMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SensorMsg.proto\022\014intelligence\"<\n\tSenso" +
      "rMsg\022\017\n\007command\030\001 \001(\005\022\020\n\010dataType\030\002 \001(\005\022" +
      "\014\n\004data\030\003 \001(\014B\030\n\006protosB\014SensorProtosP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_intelligence_SensorMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_intelligence_SensorMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_intelligence_SensorMsg_descriptor,
        new java.lang.String[] { "Command", "DataType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
