// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureMsg.proto

package protos;

public final class TemperatureProtos {
  private TemperatureProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_intelligence_TemperatureMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_intelligence_TemperatureMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024TemperatureMsg.proto\022\014intelligence\"U\n\016" +
      "TemperatureMsg\022\030\n\020temperatureLevel\030\001 \001(\002" +
      "\022\025\n\rhumidityLevel\030\002 \001(\002\022\022\n\nmetricType\030\003 " +
      "\001(\005B\035\n\006protosB\021TemperatureProtosP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_intelligence_TemperatureMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_intelligence_TemperatureMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_intelligence_TemperatureMsg_descriptor,
        new java.lang.String[] { "TemperatureLevel", "HumidityLevel", "MetricType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
