// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntelligenceMsg.proto

package com.example.intelligence.protos;

public interface IntelligenceMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intelligence.IntelligenceMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes messageID = 1;</code>
   * @return The messageID.
   */
  com.google.protobuf.ByteString getMessageID();

  /**
   * <code>bytes payload = 2;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>fixed64 checkSum = 3;</code>
   * @return The checkSum.
   */
  long getCheckSum();
}
