// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorMsg.proto

package com.example.intelligence.protos;

public interface SensorMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intelligence.SensorMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 command = 1;</code>
   * @return The command.
   */
  int getCommand();

  /**
   * <code>int32 dataType = 2;</code>
   * @return The dataType.
   */
  int getDataType();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
