// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureMsg.proto

package com.example.intelligence.protos;

public interface TemperatureMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intelligence.TemperatureMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperatureLevel = 1;</code>
   * @return The temperatureLevel.
   */
  float getTemperatureLevel();

  /**
   * <code>int32 metricType = 2;</code>
   * @return The metricType.
   */
  int getMetricType();
}
